packages:
  - 'shared/entities'
  - 'shared/database'
  - 'shared/common'
  - 'shared/event-bus'
  - 'services/user-service'
  - 'services/user-service-v2'
  - 'services/mortgage-service'
  - 'services/payment-service'
  - 'services/property-service'
  - 'services/authorizer-service'
  - 'infrastructure'
  - 'local-dev'
  - 'tests/localstack'
