packages:
  - 'shared/common'
  - 'services/authorizer-api-dynamo'
  - 'services/user-service'
  - 'services/mortgage-service'
  - 'services/payment-service'
  - 'services/property-service'
  - 'services/documents-service'
  - 'services/notification-service'
  - 'services/uploader-service'
  - 'infrastructure'
  - 'local-dev'
  - 'tests/localstack'
