# LocalStack-specific serverless config for Authorizer Service
# Usage: npx sls deploy --config serverless.localstack.yml --stage localstack

service: qshelter-authorizer-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'localstack'}
  region: us-east-1
  
  environment:
    NODE_ENV: ${self:provider.stage}
    LOCALSTACK_ENDPOINT: http://host.docker.internal:4566
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
            - ssm:PutParameter
          Resource:
            - arn:aws:ssm:${self:provider.region}:*:parameter/qshelter/${self:provider.stage}/*
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - arn:aws:secretsmanager:${self:provider.region}:*:secret:qshelter/${self:provider.stage}/*
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/*

package:
  individually: true

functions:
  authorizer:
    handler: dist/index.handler
    name: qshelter-authorizer-${self:provider.stage}
    description: Shared JWT authorizer for all QShelter services
    package:
      patterns:
        - '!**'
        - 'dist/index.mjs'
        - 'dist/index.mjs.map'

resources:
  Resources:
    AuthorizerArnParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /qshelter/${self:provider.stage}/authorizer-lambda-arn
        Description: ARN of the shared authorizer Lambda function
        Type: String
        Value: !GetAtt AuthorizerLambdaFunction.Arn

  Outputs:
    AuthorizerFunctionArn:
      Description: ARN of the shared authorizer Lambda
      Value: !GetAtt AuthorizerLambdaFunction.Arn
      Export:
        Name: QShelterAuthorizerArn-${self:provider.stage}

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - localstack
    host: http://localhost
    edgePort: 4566
    autostart: false
