-- AlterTable
ALTER TABLE `documentation_plan_steps` ADD COLUMN `allowReject` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `gateAction` ENUM('APPROVE', 'ACKNOWLEDGE', 'CONFIRM', 'CONSENT') NULL,
    ADD COLUMN `gateActor` ENUM('ADMIN', 'CUSTOMER', 'SPECIFIC_ROLE') NULL,
    ADD COLUMN `gateInstructions` TEXT NULL,
    ADD COLUMN `gateRoleId` VARCHAR(191) NULL,
    ADD COLUMN `rejectBehavior` ENUM('BLOCK', 'RESTART_STEP', 'RESTART_PHASE', 'TERMINATE') NULL,
    ADD COLUMN `requiresComment` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `stepType` ENUM('UPLOAD', 'REVIEW', 'SIGNATURE', 'APPROVAL', 'EXTERNAL_CHECK', 'WAIT', 'GENERATE_DOCUMENT', 'PRE_APPROVAL', 'UNDERWRITING', 'GATE') NOT NULL;

-- AlterTable
ALTER TABLE `documentation_steps` ADD COLUMN `allowReject` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `gateActedAt` DATETIME(3) NULL,
    ADD COLUMN `gateActedById` VARCHAR(191) NULL,
    ADD COLUMN `gateAction` ENUM('APPROVE', 'ACKNOWLEDGE', 'CONFIRM', 'CONSENT') NULL,
    ADD COLUMN `gateActor` ENUM('ADMIN', 'CUSTOMER', 'SPECIFIC_ROLE') NULL,
    ADD COLUMN `gateComment` TEXT NULL,
    ADD COLUMN `gateDecision` VARCHAR(191) NULL,
    ADD COLUMN `gateInstructions` TEXT NULL,
    ADD COLUMN `gateRoleId` VARCHAR(191) NULL,
    ADD COLUMN `rejectBehavior` ENUM('BLOCK', 'RESTART_STEP', 'RESTART_PHASE', 'TERMINATE') NULL,
    ADD COLUMN `requiresComment` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `stepType` ENUM('UPLOAD', 'REVIEW', 'SIGNATURE', 'APPROVAL', 'EXTERNAL_CHECK', 'WAIT', 'GENERATE_DOCUMENT', 'PRE_APPROVAL', 'UNDERWRITING', 'GATE') NOT NULL;

-- AlterTable
ALTER TABLE `payment_method_phase_steps` MODIFY `stepType` ENUM('UPLOAD', 'REVIEW', 'SIGNATURE', 'APPROVAL', 'EXTERNAL_CHECK', 'WAIT', 'GENERATE_DOCUMENT', 'PRE_APPROVAL', 'UNDERWRITING', 'GATE') NOT NULL;

-- AddForeignKey
ALTER TABLE `documentation_steps` ADD CONSTRAINT `documentation_steps_gateActedById_fkey` FOREIGN KEY (`gateActedById`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
