export enum MailQueueJobNames {
  SEND = 'SEND',
  SEND_TICKET = 'SEND_TICKET',
  SEND_VERIFICATION_MESSAGE = 'SEND_VERIFICATION_MESSAGE',
  SEND_PASSWORD_RESET_MESSAGE = 'SEND_PASSWORD_RESET_MESSAGE',
}