-- AlterTable
ALTER TABLE `document_approvals` MODIFY `decision` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'WAIVED', 'REVERTED') NOT NULL;

-- AlterTable
ALTER TABLE `document_reviews` MODIFY `decision` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'WAIVED', 'REVERTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `questionnaire_phase_reviews` MODIFY `decision` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'WAIVED', 'REVERTED') NOT NULL;
