-- AlterTable
ALTER TABLE `payment_method_phase_fields` MODIFY `fieldType` ENUM('TEXT', 'TEXTAREA', 'NUMBER', 'CURRENCY', 'EMAIL', 'PHONE', 'DATE', 'SELECT', 'MULTI_SELECT', 'CHECKBOX', 'RADIO', 'FILE', 'ADDRESS', 'PERCENTAGE', 'YEARS_MONTHS', 'FILE_UPLOAD') NOT NULL;

-- AlterTable
ALTER TABLE `questionnaire_fields` MODIFY `fieldType` ENUM('TEXT', 'TEXTAREA', 'NUMBER', 'CURRENCY', 'EMAIL', 'PHONE', 'DATE', 'SELECT', 'MULTI_SELECT', 'CHECKBOX', 'RADIO', 'FILE', 'ADDRESS', 'PERCENTAGE', 'YEARS_MONTHS', 'FILE_UPLOAD') NOT NULL;
