-- AlterTable
ALTER TABLE `application_refunds` MODIFY `status` ENUM('NOT_APPLICABLE', 'PENDING', 'APPROVED', 'REJECTED', 'INITIATED', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `application_terminations` MODIFY `refundStatus` ENUM('NOT_APPLICABLE', 'PENDING', 'APPROVED', 'REJECTED', 'INITIATED', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
