# Docker Compose override for development
# This file is automatically loaded by docker-compose
# Use: docker-compose up to start development environment

services:
  app:
    profiles:
      - exclude # Exclude production app service

  app-dev:
    profiles: [] # Include dev service by default
