service: mediacraft
useDotenv: true

# http://localhost:3000/dev/api
# In this offline mode, your routes will only work prepended with dev
plugins:
 # - serverless-dotenv-plugin
  - serverless-offline
 # - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  httpApi: # Use HTTP API configuration
    payload: '2.0'
  environment:
    DB_CONNECTION: mysql
    DB_HOST: ${env:HOPELIVESEC_HOPE_DB_HOST}
    DB_USERNAME: ${env:HOPELIVESEC_HOPE_DB_USERNAME}
    DB_PORT: 3306
    DB_PASSWORD: ${env:HOPELIVESEC_HOPE_DB_PASSWORD}
    DB_DATABASE: ${env:HOPELIVESEC_HOPE_DB_DATABASE}
    AWS_S3_BUCKET_NAME: ${env:HOPELIVESEC_HOPE_AWS_S3_BUCKET_NAME}
    AWS_S3_ACCESS_KEY_ID: ${env:HOPELIVESEC_AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${env:HOPELIVESEC_AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_REGION: us-east-1
    PRESIGNED_URL_TTL: 3600

functions:
  main:
    handler: dist/serverless.handler
    events:
      - httpApi: # Use HTTP API event type
          method: ANY
          path: / # Define your root path here
      - httpApi: # For proxy routes
          method: ANY
          path: /{proxy+} # Proxy route configuration
